package com.capstone.vo;

import java.util.ArrayList;
import java.util.List;

public class ProjectRolesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public ProjectRolesExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Integer value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Integer value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Integer value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Integer value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Integer> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Integer> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Integer value1, Integer value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andUsersIdIsNull() {
            addCriterion("users_id is null");
            return (Criteria) this;
        }

        public Criteria andUsersIdIsNotNull() {
            addCriterion("users_id is not null");
            return (Criteria) this;
        }

        public Criteria andUsersIdEqualTo(Integer value) {
            addCriterion("users_id =", value, "usersId");
            return (Criteria) this;
        }

        public Criteria andUsersIdNotEqualTo(Integer value) {
            addCriterion("users_id <>", value, "usersId");
            return (Criteria) this;
        }

        public Criteria andUsersIdGreaterThan(Integer value) {
            addCriterion("users_id >", value, "usersId");
            return (Criteria) this;
        }

        public Criteria andUsersIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("users_id >=", value, "usersId");
            return (Criteria) this;
        }

        public Criteria andUsersIdLessThan(Integer value) {
            addCriterion("users_id <", value, "usersId");
            return (Criteria) this;
        }

        public Criteria andUsersIdLessThanOrEqualTo(Integer value) {
            addCriterion("users_id <=", value, "usersId");
            return (Criteria) this;
        }

        public Criteria andUsersIdIn(List<Integer> values) {
            addCriterion("users_id in", values, "usersId");
            return (Criteria) this;
        }

        public Criteria andUsersIdNotIn(List<Integer> values) {
            addCriterion("users_id not in", values, "usersId");
            return (Criteria) this;
        }

        public Criteria andUsersIdBetween(Integer value1, Integer value2) {
            addCriterion("users_id between", value1, value2, "usersId");
            return (Criteria) this;
        }

        public Criteria andUsersIdNotBetween(Integer value1, Integer value2) {
            addCriterion("users_id not between", value1, value2, "usersId");
            return (Criteria) this;
        }

        public Criteria andRequiredMemIsNull() {
            addCriterion("required_mem is null");
            return (Criteria) this;
        }

        public Criteria andRequiredMemIsNotNull() {
            addCriterion("required_mem is not null");
            return (Criteria) this;
        }

        public Criteria andRequiredMemEqualTo(Integer value) {
            addCriterion("required_mem =", value, "requiredMem");
            return (Criteria) this;
        }

        public Criteria andRequiredMemNotEqualTo(Integer value) {
            addCriterion("required_mem <>", value, "requiredMem");
            return (Criteria) this;
        }

        public Criteria andRequiredMemGreaterThan(Integer value) {
            addCriterion("required_mem >", value, "requiredMem");
            return (Criteria) this;
        }

        public Criteria andRequiredMemGreaterThanOrEqualTo(Integer value) {
            addCriterion("required_mem >=", value, "requiredMem");
            return (Criteria) this;
        }

        public Criteria andRequiredMemLessThan(Integer value) {
            addCriterion("required_mem <", value, "requiredMem");
            return (Criteria) this;
        }

        public Criteria andRequiredMemLessThanOrEqualTo(Integer value) {
            addCriterion("required_mem <=", value, "requiredMem");
            return (Criteria) this;
        }

        public Criteria andRequiredMemIn(List<Integer> values) {
            addCriterion("required_mem in", values, "requiredMem");
            return (Criteria) this;
        }

        public Criteria andRequiredMemNotIn(List<Integer> values) {
            addCriterion("required_mem not in", values, "requiredMem");
            return (Criteria) this;
        }

        public Criteria andRequiredMemBetween(Integer value1, Integer value2) {
            addCriterion("required_mem between", value1, value2, "requiredMem");
            return (Criteria) this;
        }

        public Criteria andRequiredMemNotBetween(Integer value1, Integer value2) {
            addCriterion("required_mem not between", value1, value2, "requiredMem");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Integer value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Integer value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Integer value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Integer value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Integer value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Integer> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Integer> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Integer value1, Integer value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Integer value1, Integer value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andJobgroupIdIsNull() {
            addCriterion("jobgroup_id is null");
            return (Criteria) this;
        }

        public Criteria andJobgroupIdIsNotNull() {
            addCriterion("jobgroup_id is not null");
            return (Criteria) this;
        }

        public Criteria andJobgroupIdEqualTo(Integer value) {
            addCriterion("jobgroup_id =", value, "jobgroupId");
            return (Criteria) this;
        }

        public Criteria andJobgroupIdNotEqualTo(Integer value) {
            addCriterion("jobgroup_id <>", value, "jobgroupId");
            return (Criteria) this;
        }

        public Criteria andJobgroupIdGreaterThan(Integer value) {
            addCriterion("jobgroup_id >", value, "jobgroupId");
            return (Criteria) this;
        }

        public Criteria andJobgroupIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("jobgroup_id >=", value, "jobgroupId");
            return (Criteria) this;
        }

        public Criteria andJobgroupIdLessThan(Integer value) {
            addCriterion("jobgroup_id <", value, "jobgroupId");
            return (Criteria) this;
        }

        public Criteria andJobgroupIdLessThanOrEqualTo(Integer value) {
            addCriterion("jobgroup_id <=", value, "jobgroupId");
            return (Criteria) this;
        }

        public Criteria andJobgroupIdIn(List<Integer> values) {
            addCriterion("jobgroup_id in", values, "jobgroupId");
            return (Criteria) this;
        }

        public Criteria andJobgroupIdNotIn(List<Integer> values) {
            addCriterion("jobgroup_id not in", values, "jobgroupId");
            return (Criteria) this;
        }

        public Criteria andJobgroupIdBetween(Integer value1, Integer value2) {
            addCriterion("jobgroup_id between", value1, value2, "jobgroupId");
            return (Criteria) this;
        }

        public Criteria andJobgroupIdNotBetween(Integer value1, Integer value2) {
            addCriterion("jobgroup_id not between", value1, value2, "jobgroupId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_roles
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 02 09:48:40 KST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}