package com.capstone.vo;

import java.util.Date;

public class ProjectSchedule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_schedule.ID
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_schedule.PROJECT_ID
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_schedule.TITLE
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_schedule.START_DATE
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_schedule.END_DATE
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_schedule.START_TIME
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    private String startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_schedule.END_TIME
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_schedule.CONTENT
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_schedule.ID
     *
     * @return the value of project_schedule.ID
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_schedule.ID
     *
     * @param id the value for project_schedule.ID
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_schedule.PROJECT_ID
     *
     * @return the value of project_schedule.PROJECT_ID
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_schedule.PROJECT_ID
     *
     * @param projectId the value for project_schedule.PROJECT_ID
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_schedule.TITLE
     *
     * @return the value of project_schedule.TITLE
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_schedule.TITLE
     *
     * @param title the value for project_schedule.TITLE
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_schedule.START_DATE
     *
     * @return the value of project_schedule.START_DATE
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_schedule.START_DATE
     *
     * @param startDate the value for project_schedule.START_DATE
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_schedule.END_DATE
     *
     * @return the value of project_schedule.END_DATE
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_schedule.END_DATE
     *
     * @param endDate the value for project_schedule.END_DATE
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_schedule.START_TIME
     *
     * @return the value of project_schedule.START_TIME
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_schedule.START_TIME
     *
     * @param startTime the value for project_schedule.START_TIME
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_schedule.END_TIME
     *
     * @return the value of project_schedule.END_TIME
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_schedule.END_TIME
     *
     * @param endTime the value for project_schedule.END_TIME
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_schedule.CONTENT
     *
     * @return the value of project_schedule.CONTENT
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_schedule.CONTENT
     *
     * @param content the value for project_schedule.CONTENT
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    public void setContent(String content) {
        this.content = content;
    }
}