package com.capstone.vo;

public class ProjectRoles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_roles.id
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_roles.project_id
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_roles.users_id
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    private Integer usersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_roles.required_mem
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    private Integer requiredMem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_roles.count
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_roles.jobgroup_id
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    private Integer jobgroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_roles.id
     *
     * @return the value of project_roles.id
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_roles.id
     *
     * @param id the value for project_roles.id
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_roles.project_id
     *
     * @return the value of project_roles.project_id
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_roles.project_id
     *
     * @param projectId the value for project_roles.project_id
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_roles.users_id
     *
     * @return the value of project_roles.users_id
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public Integer getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_roles.users_id
     *
     * @param usersId the value for project_roles.users_id
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_roles.required_mem
     *
     * @return the value of project_roles.required_mem
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public Integer getRequiredMem() {
        return requiredMem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_roles.required_mem
     *
     * @param requiredMem the value for project_roles.required_mem
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public void setRequiredMem(Integer requiredMem) {
        this.requiredMem = requiredMem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_roles.count
     *
     * @return the value of project_roles.count
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_roles.count
     *
     * @param count the value for project_roles.count
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_roles.jobgroup_id
     *
     * @return the value of project_roles.jobgroup_id
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public Integer getJobgroupId() {
        return jobgroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_roles.jobgroup_id
     *
     * @param jobgroupId the value for project_roles.jobgroup_id
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    public void setJobgroupId(Integer jobgroupId) {
        this.jobgroupId = jobgroupId;
    }
}