package com.capstone.vo;

import java.util.Date;

public class Projects {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column projects.ID
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column projects.NAME
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column projects.DESC
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	private String desc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column projects.TOPIC
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	private String topic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column projects.REGION
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	private String region;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column projects.PHASE
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	private String phase;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column projects.START_DATE
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	private Date startDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column projects.END_DATE
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column projects.USER_ID
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	private Integer userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column projects.ID
	 * @return  the value of projects.ID
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column projects.ID
	 * @param id  the value for projects.ID
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column projects.NAME
	 * @return  the value of projects.NAME
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column projects.NAME
	 * @param name  the value for projects.NAME
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column projects.DESC
	 * @return  the value of projects.DESC
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column projects.DESC
	 * @param desc  the value for projects.DESC
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column projects.TOPIC
	 * @return  the value of projects.TOPIC
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public String getTopic() {
		return topic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column projects.TOPIC
	 * @param topic  the value for projects.TOPIC
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public void setTopic(String topic) {
		this.topic = topic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column projects.REGION
	 * @return  the value of projects.REGION
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public String getRegion() {
		return region;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column projects.REGION
	 * @param region  the value for projects.REGION
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public void setRegion(String region) {
		this.region = region;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column projects.PHASE
	 * @return  the value of projects.PHASE
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public String getPhase() {
		return phase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column projects.PHASE
	 * @param phase  the value for projects.PHASE
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public void setPhase(String phase) {
		this.phase = phase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column projects.START_DATE
	 * @return  the value of projects.START_DATE
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column projects.START_DATE
	 * @param startDate  the value for projects.START_DATE
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column projects.END_DATE
	 * @return  the value of projects.END_DATE
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column projects.END_DATE
	 * @param endDate  the value for projects.END_DATE
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column projects.USER_ID
	 * @return  the value of projects.USER_ID
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column projects.USER_ID
	 * @param userId  the value for projects.USER_ID
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}