package com.capstone.vo;

public class ProjectsWithBLOBs extends Projects {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column projects.CONTENT
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column projects.RESULT
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	private String result;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column projects.CONTENT
	 * @return  the value of projects.CONTENT
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column projects.CONTENT
	 * @param content  the value for projects.CONTENT
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column projects.RESULT
	 * @return  the value of projects.RESULT
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public String getResult() {
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column projects.RESULT
	 * @param result  the value for projects.RESULT
	 * @mbg.generated  Mon Nov 18 08:18:12 KST 2024
	 */
	public void setResult(String result) {
		this.result = result;
	}
}