package com.capstone.vo;

public class UsersInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_info.ID
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_info.USER_ID
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_info.PASSWORD
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_info.NAME
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_info.CONTACT
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_info.INTRO
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_info.STRENGTH
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    private String strength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_info.REGION
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_info.PROFILE_PIC
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    private String profilePic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_info.ID
     *
     * @return the value of users_info.ID
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_info.ID
     *
     * @param id the value for users_info.ID
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_info.USER_ID
     *
     * @return the value of users_info.USER_ID
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_info.USER_ID
     *
     * @param userId the value for users_info.USER_ID
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_info.PASSWORD
     *
     * @return the value of users_info.PASSWORD
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_info.PASSWORD
     *
     * @param password the value for users_info.PASSWORD
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_info.NAME
     *
     * @return the value of users_info.NAME
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_info.NAME
     *
     * @param name the value for users_info.NAME
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_info.CONTACT
     *
     * @return the value of users_info.CONTACT
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_info.CONTACT
     *
     * @param contact the value for users_info.CONTACT
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_info.INTRO
     *
     * @return the value of users_info.INTRO
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_info.INTRO
     *
     * @param intro the value for users_info.INTRO
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_info.STRENGTH
     *
     * @return the value of users_info.STRENGTH
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    public String getStrength() {
        return strength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_info.STRENGTH
     *
     * @param strength the value for users_info.STRENGTH
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    public void setStrength(String strength) {
        this.strength = strength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_info.REGION
     *
     * @return the value of users_info.REGION
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_info.REGION
     *
     * @param region the value for users_info.REGION
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_info.PROFILE_PIC
     *
     * @return the value of users_info.PROFILE_PIC
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    public String getProfilePic() {
        return profilePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_info.PROFILE_PIC
     *
     * @param profilePic the value for users_info.PROFILE_PIC
     *
     * @mbg.generated Mon Oct 28 04:56:03 KST 2024
     */
    public void setProfilePic(String profilePic) {
        this.profilePic = profilePic;
    }
}