package com.capstone.vo;

public class UserProject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_project.ID
	 * @mbg.generated  Mon Nov 25 06:50:05 KST 2024
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_project.USER_ID
	 * @mbg.generated  Mon Nov 25 06:50:05 KST 2024
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_project.PROJECTROLE_ID
	 * @mbg.generated  Mon Nov 25 06:50:05 KST 2024
	 */
	private Integer projectroleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_project.ID
	 * @return  the value of user_project.ID
	 * @mbg.generated  Mon Nov 25 06:50:05 KST 2024
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_project.ID
	 * @param id  the value for user_project.ID
	 * @mbg.generated  Mon Nov 25 06:50:05 KST 2024
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_project.USER_ID
	 * @return  the value of user_project.USER_ID
	 * @mbg.generated  Mon Nov 25 06:50:05 KST 2024
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_project.USER_ID
	 * @param userId  the value for user_project.USER_ID
	 * @mbg.generated  Mon Nov 25 06:50:05 KST 2024
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_project.PROJECTROLE_ID
	 * @return  the value of user_project.PROJECTROLE_ID
	 * @mbg.generated  Mon Nov 25 06:50:05 KST 2024
	 */
	public Integer getProjectroleId() {
		return projectroleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_project.PROJECTROLE_ID
	 * @param projectroleId  the value for user_project.PROJECTROLE_ID
	 * @mbg.generated  Mon Nov 25 06:50:05 KST 2024
	 */
	public void setProjectroleId(Integer projectroleId) {
		this.projectroleId = projectroleId;
	}
}