package com.capstone.vo;

import java.util.ArrayList;
import java.util.List;

public class UsersInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	public UsersInfoExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("USER_ID =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("USER_ID <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("USER_ID >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("USER_ID >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("USER_ID <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("USER_ID <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("USER_ID like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("USER_ID not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("USER_ID in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("USER_ID not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("USER_ID between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("USER_ID not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("PASSWORD is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("PASSWORD is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("PASSWORD =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("PASSWORD <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("PASSWORD >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("PASSWORD >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("PASSWORD <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("PASSWORD <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("PASSWORD like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("PASSWORD not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("PASSWORD in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("PASSWORD not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("PASSWORD between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("PASSWORD not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("NAME is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("NAME is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("NAME =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("NAME <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("NAME >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("NAME >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("NAME <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("NAME <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("NAME like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("NAME not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("NAME in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("NAME not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("NAME between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("NAME not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andContactIsNull() {
			addCriterion("CONTACT is null");
			return (Criteria) this;
		}

		public Criteria andContactIsNotNull() {
			addCriterion("CONTACT is not null");
			return (Criteria) this;
		}

		public Criteria andContactEqualTo(String value) {
			addCriterion("CONTACT =", value, "contact");
			return (Criteria) this;
		}

		public Criteria andContactNotEqualTo(String value) {
			addCriterion("CONTACT <>", value, "contact");
			return (Criteria) this;
		}

		public Criteria andContactGreaterThan(String value) {
			addCriterion("CONTACT >", value, "contact");
			return (Criteria) this;
		}

		public Criteria andContactGreaterThanOrEqualTo(String value) {
			addCriterion("CONTACT >=", value, "contact");
			return (Criteria) this;
		}

		public Criteria andContactLessThan(String value) {
			addCriterion("CONTACT <", value, "contact");
			return (Criteria) this;
		}

		public Criteria andContactLessThanOrEqualTo(String value) {
			addCriterion("CONTACT <=", value, "contact");
			return (Criteria) this;
		}

		public Criteria andContactLike(String value) {
			addCriterion("CONTACT like", value, "contact");
			return (Criteria) this;
		}

		public Criteria andContactNotLike(String value) {
			addCriterion("CONTACT not like", value, "contact");
			return (Criteria) this;
		}

		public Criteria andContactIn(List<String> values) {
			addCriterion("CONTACT in", values, "contact");
			return (Criteria) this;
		}

		public Criteria andContactNotIn(List<String> values) {
			addCriterion("CONTACT not in", values, "contact");
			return (Criteria) this;
		}

		public Criteria andContactBetween(String value1, String value2) {
			addCriterion("CONTACT between", value1, value2, "contact");
			return (Criteria) this;
		}

		public Criteria andContactNotBetween(String value1, String value2) {
			addCriterion("CONTACT not between", value1, value2, "contact");
			return (Criteria) this;
		}

		public Criteria andIntroIsNull() {
			addCriterion("INTRO is null");
			return (Criteria) this;
		}

		public Criteria andIntroIsNotNull() {
			addCriterion("INTRO is not null");
			return (Criteria) this;
		}

		public Criteria andIntroEqualTo(String value) {
			addCriterion("INTRO =", value, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroNotEqualTo(String value) {
			addCriterion("INTRO <>", value, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroGreaterThan(String value) {
			addCriterion("INTRO >", value, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroGreaterThanOrEqualTo(String value) {
			addCriterion("INTRO >=", value, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroLessThan(String value) {
			addCriterion("INTRO <", value, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroLessThanOrEqualTo(String value) {
			addCriterion("INTRO <=", value, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroLike(String value) {
			addCriterion("INTRO like", value, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroNotLike(String value) {
			addCriterion("INTRO not like", value, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroIn(List<String> values) {
			addCriterion("INTRO in", values, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroNotIn(List<String> values) {
			addCriterion("INTRO not in", values, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroBetween(String value1, String value2) {
			addCriterion("INTRO between", value1, value2, "intro");
			return (Criteria) this;
		}

		public Criteria andIntroNotBetween(String value1, String value2) {
			addCriterion("INTRO not between", value1, value2, "intro");
			return (Criteria) this;
		}

		public Criteria andStrengthIsNull() {
			addCriterion("STRENGTH is null");
			return (Criteria) this;
		}

		public Criteria andStrengthIsNotNull() {
			addCriterion("STRENGTH is not null");
			return (Criteria) this;
		}

		public Criteria andStrengthEqualTo(String value) {
			addCriterion("STRENGTH =", value, "strength");
			return (Criteria) this;
		}

		public Criteria andStrengthNotEqualTo(String value) {
			addCriterion("STRENGTH <>", value, "strength");
			return (Criteria) this;
		}

		public Criteria andStrengthGreaterThan(String value) {
			addCriterion("STRENGTH >", value, "strength");
			return (Criteria) this;
		}

		public Criteria andStrengthGreaterThanOrEqualTo(String value) {
			addCriterion("STRENGTH >=", value, "strength");
			return (Criteria) this;
		}

		public Criteria andStrengthLessThan(String value) {
			addCriterion("STRENGTH <", value, "strength");
			return (Criteria) this;
		}

		public Criteria andStrengthLessThanOrEqualTo(String value) {
			addCriterion("STRENGTH <=", value, "strength");
			return (Criteria) this;
		}

		public Criteria andStrengthLike(String value) {
			addCriterion("STRENGTH like", value, "strength");
			return (Criteria) this;
		}

		public Criteria andStrengthNotLike(String value) {
			addCriterion("STRENGTH not like", value, "strength");
			return (Criteria) this;
		}

		public Criteria andStrengthIn(List<String> values) {
			addCriterion("STRENGTH in", values, "strength");
			return (Criteria) this;
		}

		public Criteria andStrengthNotIn(List<String> values) {
			addCriterion("STRENGTH not in", values, "strength");
			return (Criteria) this;
		}

		public Criteria andStrengthBetween(String value1, String value2) {
			addCriterion("STRENGTH between", value1, value2, "strength");
			return (Criteria) this;
		}

		public Criteria andStrengthNotBetween(String value1, String value2) {
			addCriterion("STRENGTH not between", value1, value2, "strength");
			return (Criteria) this;
		}

		public Criteria andRegionIsNull() {
			addCriterion("REGION is null");
			return (Criteria) this;
		}

		public Criteria andRegionIsNotNull() {
			addCriterion("REGION is not null");
			return (Criteria) this;
		}

		public Criteria andRegionEqualTo(String value) {
			addCriterion("REGION =", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionNotEqualTo(String value) {
			addCriterion("REGION <>", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionGreaterThan(String value) {
			addCriterion("REGION >", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionGreaterThanOrEqualTo(String value) {
			addCriterion("REGION >=", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionLessThan(String value) {
			addCriterion("REGION <", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionLessThanOrEqualTo(String value) {
			addCriterion("REGION <=", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionLike(String value) {
			addCriterion("REGION like", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionNotLike(String value) {
			addCriterion("REGION not like", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionIn(List<String> values) {
			addCriterion("REGION in", values, "region");
			return (Criteria) this;
		}

		public Criteria andRegionNotIn(List<String> values) {
			addCriterion("REGION not in", values, "region");
			return (Criteria) this;
		}

		public Criteria andRegionBetween(String value1, String value2) {
			addCriterion("REGION between", value1, value2, "region");
			return (Criteria) this;
		}

		public Criteria andRegionNotBetween(String value1, String value2) {
			addCriterion("REGION not between", value1, value2, "region");
			return (Criteria) this;
		}

		public Criteria andProfilePicIsNull() {
			addCriterion("PROFILE_PIC is null");
			return (Criteria) this;
		}

		public Criteria andProfilePicIsNotNull() {
			addCriterion("PROFILE_PIC is not null");
			return (Criteria) this;
		}

		public Criteria andProfilePicEqualTo(String value) {
			addCriterion("PROFILE_PIC =", value, "profilePic");
			return (Criteria) this;
		}

		public Criteria andProfilePicNotEqualTo(String value) {
			addCriterion("PROFILE_PIC <>", value, "profilePic");
			return (Criteria) this;
		}

		public Criteria andProfilePicGreaterThan(String value) {
			addCriterion("PROFILE_PIC >", value, "profilePic");
			return (Criteria) this;
		}

		public Criteria andProfilePicGreaterThanOrEqualTo(String value) {
			addCriterion("PROFILE_PIC >=", value, "profilePic");
			return (Criteria) this;
		}

		public Criteria andProfilePicLessThan(String value) {
			addCriterion("PROFILE_PIC <", value, "profilePic");
			return (Criteria) this;
		}

		public Criteria andProfilePicLessThanOrEqualTo(String value) {
			addCriterion("PROFILE_PIC <=", value, "profilePic");
			return (Criteria) this;
		}

		public Criteria andProfilePicLike(String value) {
			addCriterion("PROFILE_PIC like", value, "profilePic");
			return (Criteria) this;
		}

		public Criteria andProfilePicNotLike(String value) {
			addCriterion("PROFILE_PIC not like", value, "profilePic");
			return (Criteria) this;
		}

		public Criteria andProfilePicIn(List<String> values) {
			addCriterion("PROFILE_PIC in", values, "profilePic");
			return (Criteria) this;
		}

		public Criteria andProfilePicNotIn(List<String> values) {
			addCriterion("PROFILE_PIC not in", values, "profilePic");
			return (Criteria) this;
		}

		public Criteria andProfilePicBetween(String value1, String value2) {
			addCriterion("PROFILE_PIC between", value1, value2, "profilePic");
			return (Criteria) this;
		}

		public Criteria andProfilePicNotBetween(String value1, String value2) {
			addCriterion("PROFILE_PIC not between", value1, value2, "profilePic");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users_info
     *
     * @mbg.generated do_not_delete_during_merge Mon Oct 28 04:56:03 KST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}