package com.capstone.dao;

import com.capstone.vo.ProjectRoles;
import com.capstone.vo.ProjectRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    long countByExample(ProjectRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    int deleteByExample(ProjectRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    int insert(ProjectRoles row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    int insertSelective(ProjectRoles row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    List<ProjectRoles> selectByExample(ProjectRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    ProjectRoles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    int updateByExampleSelective(@Param("row") ProjectRoles row, @Param("example") ProjectRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    int updateByExample(@Param("row") ProjectRoles row, @Param("example") ProjectRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    int updateByPrimaryKeySelective(ProjectRoles row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_roles
     *
     * @mbg.generated Mon Dec 02 09:48:40 KST 2024
     */
    int updateByPrimaryKey(ProjectRoles row);
}