package com.capstone.dao;

import com.capstone.vo.ProjectSchedule;
import com.capstone.vo.ProjectScheduleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_schedule
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    long countByExample(ProjectScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_schedule
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    int deleteByExample(ProjectScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_schedule
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_schedule
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    int insert(ProjectSchedule row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_schedule
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    int insertSelective(ProjectSchedule row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_schedule
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    List<ProjectSchedule> selectByExampleWithBLOBs(ProjectScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_schedule
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    List<ProjectSchedule> selectByExample(ProjectScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_schedule
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    ProjectSchedule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_schedule
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    int updateByExampleSelective(@Param("row") ProjectSchedule row, @Param("example") ProjectScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_schedule
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    int updateByExampleWithBLOBs(@Param("row") ProjectSchedule row, @Param("example") ProjectScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_schedule
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    int updateByExample(@Param("row") ProjectSchedule row, @Param("example") ProjectScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_schedule
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    int updateByPrimaryKeySelective(ProjectSchedule row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_schedule
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    int updateByPrimaryKeyWithBLOBs(ProjectSchedule row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_schedule
     *
     * @mbg.generated Mon Nov 25 07:46:55 KST 2024
     */
    int updateByPrimaryKey(ProjectSchedule row);
}