package com.capstone.dao;

import com.capstone.vo.UserProject;
import com.capstone.vo.UserProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserProjectMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_project
	 * @mbg.generated  Mon Nov 25 06:50:05 KST 2024
	 */
	long countByExample(UserProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_project
	 * @mbg.generated  Mon Nov 25 06:50:05 KST 2024
	 */
	int deleteByExample(UserProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_project
	 * @mbg.generated  Mon Nov 25 06:50:05 KST 2024
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_project
	 * @mbg.generated  Mon Nov 25 06:50:05 KST 2024
	 */
	int insert(UserProject row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_project
	 * @mbg.generated  Mon Nov 25 06:50:05 KST 2024
	 */
	int insertSelective(UserProject row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_project
	 * @mbg.generated  Mon Nov 25 06:50:05 KST 2024
	 */
	List<UserProject> selectByExample(UserProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_project
	 * @mbg.generated  Mon Nov 25 06:50:05 KST 2024
	 */
	UserProject selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_project
	 * @mbg.generated  Mon Nov 25 06:50:05 KST 2024
	 */
	int updateByExampleSelective(@Param("row") UserProject row, @Param("example") UserProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_project
	 * @mbg.generated  Mon Nov 25 06:50:05 KST 2024
	 */
	int updateByExample(@Param("row") UserProject row, @Param("example") UserProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_project
	 * @mbg.generated  Mon Nov 25 06:50:05 KST 2024
	 */
	int updateByPrimaryKeySelective(UserProject row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_project
	 * @mbg.generated  Mon Nov 25 06:50:05 KST 2024
	 */
	int updateByPrimaryKey(UserProject row);

	/**
     * 이하부터 개발자가 생성한 코드
     */
    int deleteById(UserProject row);
}