package com.capstone.dao;

import com.capstone.vo.Users;
import com.capstone.vo.UsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Mon Oct 28 02:51:34 KST 2024
	 */
	long countByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Mon Oct 28 02:51:34 KST 2024
	 */
	int deleteByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Mon Oct 28 02:51:34 KST 2024
	 */
	int insert(Users row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Mon Oct 28 02:51:34 KST 2024
	 */
	int insertSelective(Users row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Mon Oct 28 02:51:34 KST 2024
	 */
	List<Users> selectByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Mon Oct 28 02:51:34 KST 2024
	 */
	int updateByExampleSelective(@Param("row") Users row, @Param("example") UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Mon Oct 28 02:51:34 KST 2024
	 */
	int updateByExample(@Param("row") Users row, @Param("example") UsersExample example);
}