package com.capstone.dao;

import com.capstone.vo.UsersInfo;
import com.capstone.vo.UsersInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

public interface UsersInfoMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	long countByExample(UsersInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	int deleteByExample(UsersInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	int insert(UsersInfo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	int insertSelective(UsersInfo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	List<UsersInfo> selectByExample(UsersInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	UsersInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	int updateByExampleSelective(@Param("row") UsersInfo row, @Param("example") UsersInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	int updateByExample(@Param("row") UsersInfo row, @Param("example") UsersInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	int updateByPrimaryKeySelective(UsersInfo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_info
	 * @mbg.generated  Sun Nov 17 19:11:40 KST 2024
	 */
	int updateByPrimaryKey(UsersInfo row);

	/**
     * 이하부터 개발자가 생성한 코드
     */
    UsersInfo findByUserId(String userId);

}